[versions]
gradleplugin = "7.3.1"
kotlin = "1.7.10"

compileSdk = "31"
targetSdk = "31"
minSdk = "21"

appcompat = "1.4.2"
material = "1.6.1"
hilt = "2.44"
ktx-core = "1.8.0"
ktx-fragment = "1.5.3"
ktx-lifecycle = "2.5.1"
room = "2.4.3"
navigation = "2.5.3"
retrofit = "2.9.0"
okhttp-logging = "4.9.3"
junit = "4.13.2"
android-junit = "1.1.3"
android-espresso = "3.4.0"

[libraries]
android-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
android-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
android-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
android-ktx-core = { module = "androidx.core:core-ktx", version.ref = "ktx-core" }
android-ktx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "ktx-fragment" }
android-ktx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "ktx-lifecycle" }
android-ktx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "ktx-lifecycle" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-logging" }
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigation" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigation" }
test-junit = { module = "junit:junit", version.ref = "junit" }
android-test-junit = { module = "androidx.test.ext:junit", version.ref = "android-junit" }
android-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "android-espresso" }

[bundles]
room = ["room-ktx", "room-runtime"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
android-library = { id = "com.android.library", version.ref = "gradleplugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
navigation-safeargs-plugin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
